name: simple_flutterble
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0


environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_blue_plus: ^1.32.4
  permission_handler: ^11.3.0
  share_plus: ^11.0.0
  csv: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
